sr: 16000
raw_data:
  path: /home/thomas/Dir/ccny/ccny-masters-thesis/raw-data
  datasets:
    train:
      LibriSpeech:
        - dev-clean
        - dev-other
    test:
      LibriSpeech:
        - test-clean
feature_data:
  path: /home/thomas/Dir/ccny/ccny-masters-thesis/feature-data
  N: 20 # speakers per batch
  M: 10 # utterances per batch per speaker
features:
  type: melspectrogram
  window_length: 0.28125
  overlap_percent: 0.5 # out of 1.0
  frame_length: 0.025  # seconds
  hop_length: 0.01     # seconds
  n_fft: 512
  n_mels: 40
  trim_top_db: 20
train:
  epochs: 20
  network:
    optimizer:
      type: Adam
      lr: 0.001
    dropout: 0.1
    layers:
      - conv1d:
          filters: 64
          kernel_size: 16
          use_batchnorm: True
      - conv1d:
          filters: 64
          kernel_size: 5
          use_batchnorm: True
      - conv1d:
          filters: 32
          kernel_size: 2
          use_batchnorm: True
      # - lstm:
      #     units: 8
      - flatten
      - fc:
          nodes: 512
      - fc:
          nodes: 512
      - embedding:
          nodes: 32
      - similarity_matrix # TODO: add initial values
    callbacks:
      tensorboard:
        log_dir: .tensorboard_logs
        write_images: True
      # lr_scheduler:
      #   cutoff_epoch: 25
      #   decay: exponential
      csv_logger:
        dir: training_logs
      checkpoint:
        dir: model_checkpoints
