sr: 16000
raw_data:
  path: /home/thomas/Dir/ccny/ccny-masters-thesis/raw-data
  datasets:
    LibriSpeech:
      - dev-clean
      - dev-other
      # - test-clean
      - test-other
      - train-clean-100
feature_data:
  path: /home/thomas/Dir/ccny/ccny-masters-thesis/feature-data
  train_split: 0.65
  speakers_per_batch: 8
  utterances_per_speaker: 4
features:
  type: melspectrogram
  window_length: 1.2   # seconds
  overlap_percent: 0.5 # out of 1.0
  frame_length: 0.025  # seconds
  hop_length: 0.01     # seconds
  n_fft: 512
  n_mels: 40
  trim_top_db: 20
train:
  epochs: 50
  network:
    optimizer:
      type: Adam
      lr: 0.001
    dropout: 0.1
    layers:
      - lstm:
          units: 128
          return_sequences: True
      - lstm:
          units: 128
          return_sequences: False
      - embedding:
          nodes: 256
      - similarity_matrix:
          embedding_length: 256
    callbacks:
      # lr_scheduler:
      #   cutoff_epoch: 25
      #   decay: exponential
      csv_logger:
        dir: training_logs
      checkpoint:
        dir: model_checkpoints
